import os
import time
from typing import Dict
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader
from config import settings
from logger import logger

def generate_report(
    video_path: str,
    candidate_name: str,
    role: str,
    features: Dict,
    scores: Dict,
    report_id: str
):
    logger.info(f"Generating report: {report_id}")
    
    os.makedirs(settings.REPORT_DIR, exist_ok=True)
    report_path = os.path.join(settings.REPORT_DIR, f"{report_id}.pdf")
    
    try:
        c = canvas.Canvas(report_path, pagesize=letter)
        width, height = letter
        
        # Logo
        try:
            logo = ImageReader("logo.jpg")
            c.drawImage(logo, 50, height - 80, width=60, height=60)
        except:
            pass
        
        c.setFont("Helvetica-Bold", 28)
        c.setFillColor(colors.HexColor("#1A1A1A"))
        c.drawString(120, height - 50, "PARAGON IRIS")
        
        c.setFont("Helvetica", 12)
        c.setFillColor(colors.HexColor("#6C2BD9"))
        c.drawString(120, height - 70, "Executive Interview Intelligence")
        
        c.setFont("Helvetica-Bold", 14)
        c.setFillColor(colors.black)
        c.drawString(50, height - 120, "CANDIDATE REPORT")
        
        c.setFont("Helvetica", 11)
        c.setFillColor(colors.black)
        c.drawString(50, height - 145, f"Candidate: {candidate_name}")
        c.drawString(50, height - 162, f"Role: {role}")
        c.drawString(50, height - 179, f"Date: {time.strftime('%Y-%m-%d %H:%M')}")
        c.drawString(50, height - 196, f"Report ID: {report_id}")
        
        overall = scores.get('overall', 0)
        
        x_center = width - 150
        y_center = height - 160
        radius = 60
        
        if overall >= 70:
            color = colors.HexColor("#2ECC71")
        elif overall >= 50:
            color = colors.HexColor("#F39C12")
        else:
            color = colors.HexColor("#E74C3C")
        
        c.setFillColor(color)
        c.circle(x_center, y_center, radius, fill=1)
        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 36)
        c.drawCentredString(x_center, y_center - 12, str(round(overall)))
        c.setFont("Helvetica", 10)
        c.drawCentredString(x_center, y_center - 35, "OVERALL")
        
        y = height - 240
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y, "SCORES BREAKDOWN")
        y -= 25
        
        sub_scores = [
            ('Composure', scores.get('composure', 0)),
            ('Communication', scores.get('communication', 0)),
            ('Presence', scores.get('presence', 0)),
            ('Professionalism', scores.get('professionalism', 0))
        ]
        
        for label, value in sub_scores:
            c.setFont("Helvetica", 11)
            c.drawString(50, y, label)
            
            bar_width = 300
            bar_height = 16
            
            c.setFillColor(colors.HexColor("#E8E8E8"))
            c.rect(160, y - 10, bar_width, bar_height, fill=1)
            
            if value >= 70:
                bar_color = colors.HexColor("#2ECC71")
            elif value >= 50:
                bar_color = colors.HexColor("#F39C12")
            else:
                bar_color = colors.HexColor("#E74C3C")
            
            c.setFillColor(bar_color)
            c.rect(160, y - 10, (value / 100) * bar_width, bar_height, fill=1)
            
            c.setFillColor(colors.black)
            c.drawString(480, y, f"{round(value)}/100")
            y -= 28
        
        y -= 15
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y, "KEY STRENGTHS")
        y -= 25
        
        strengths = [
            "✓ Strong eye contact maintained throughout interview",
            "✓ Clear communication with minimal filler words",
            "✓ Professional environment setup",
            "✓ Confident posture with good engagement"
        ]
        
        c.setFont("Helvetica", 11)
        for strength in strengths:
            c.drawString(70, y, strength)
            y -= 20
        
        c.setFont("Helvetica", 9)
        c.setFillColor(colors.HexColor("#888888"))
        c.drawString(50, 50, "Generated by Paragon IRIS - The standard for executive hiring")
        c.drawString(50, 35, "Confidential - For internal use only")
        
        c.save()
        logger.info(f"Report saved: {report_path}")
        
    except Exception as e:
        logger.error(f"Report generation failed: {e}")
        raise